import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import { Cube } from '../common/components/cube'
import css from './index.module.scss'
import dynamic from 'next/dynamic'
import React from 'react'
import { useEffect } from 'react'

const Cube = dynamic(() => import('common/components/cube'), {
  ssr: false,
})

const Home: NextPage = () => {
  return (
    <div className={css.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={css.main}>
        {/* Cube logic is loaded dynamically and its scripts need the element to exist at initiation, so we add a div to instantiate on: */}
        <div className={css['cube']} id="cube" />
        <Cube />
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
